name: "Hacktoberfest Issue"
description: "Template for Hacktoberfest contributions to the GenBr Extension"
title: "[Hacktoberfest] "
labels: 
  - "hacktoberfest"
  - "good first issue"
  - "help wanted"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Description
        This issue is part of **Hacktoberfest**! 🎉
        We are looking for contributions to the **GenBr Extension**, a Brazilian placeholder data generator for testing and mock data.

        > Briefly explain what needs to be done. Examples:
        > - Add new data types (CPF, CNPJ, fake addresses)
        > - Fix bugs in translations or UI display
        > - Improve the UI/UX of the extension popup
        > - Refactor code or improve documentation

  - type: textarea
    id: contribution-details
    attributes:
      label: "Contribution Details"
      description: "Write here what you plan to implement or change."
      placeholder: "Describe your changes..."

  - type: markdown
    attributes:
      value: |
        ## 🛠 How to contribute
        1. Fork this repository
        2. Create a branch: `git checkout -b my-contribution`
        3. Make your changes
        4. Commit your work
        5. Push to your fork
        6. Open a Pull Request to the main repository and link this issue
